services:
  - type: web
    name: gold-currency-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: BRSAPI_KEY
        sync: false
